export const enum CFAType {
  ZERO_CFA = 'ZERO_CFA',
  ZERO_ONE_CFA = 'ZERO_ONE_CFA',
  VANILLA_ZERO_ONE_CFA = 'VANILLA_ZERO_ONE_CFA',
  N_CFA = 'N_CFA',
  VANILLA_N_CFA = 'VANILLA_N_CFA',
  ZERO_CONTAINER_CFA = 'ZERO_CONTAINER_CFA',
  ZERO_ONE_CONTAINER_CFA = 'ZERO_ONE_CONTAINER_CFA',
  VANILLA_ZERO_ONE_CONTAINER_CFA = 'VANILLA_ZERO_ONE_CONTAINER_CFA'
}
