export const enum ReflectionOptions {
  FULL = 'FULL',
  NO_FLOW_TO_CASTS = 'NO_FLOW_TO_CASTS',
  NO_FLOW_TO_CASTS_NO_METHOD_INVOKE = 'NO_FLOW_TO_CASTS_NO_METHOD_INVOKE',
  NO_METHOD_INVOKE = 'NO_METHOD_INVOKE',
  NO_STRING_CONSTANTS = 'NO_STRING_CONSTANTS',
  NONE = 'NONE',
  ONE_FLOW_TO_CASTS_NO_METHOD_INVOKE = 'ONE_FLOW_TO_CASTS_NO_METHOD_INVOKE'
}
